// Code generated by protoc-gen-go.
// source: simple_test.proto
// DO NOT EDIT!

/*
Package protorec is a generated protocol buffer package.

It is generated from these files:
	simple_test.proto

It has these top-level messages:
	TestMsg
*/
package protorec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestMsg struct {
	F1 string  `protobuf:"bytes,1,opt,name=f1" json:"f1,omitempty"`
	F2 int32   `protobuf:"varint,10,opt,name=f2" json:"f2,omitempty"`
	F4 []byte  `protobuf:"bytes,99,opt,name=f4,proto3" json:"f4,omitempty"`
	F3 uint64  `protobuf:"fixed64,14,opt,name=f3" json:"f3,omitempty"`
	F5 float64 `protobuf:"fixed64,108,opt,name=f5" json:"f5,omitempty"`
}

func (m *TestMsg) Reset()                    { *m = TestMsg{} }
func (m *TestMsg) String() string            { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()               {}
func (*TestMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMsg) GetF1() string {
	if m != nil {
		return m.F1
	}
	return ""
}

func (m *TestMsg) GetF2() int32 {
	if m != nil {
		return m.F2
	}
	return 0
}

func (m *TestMsg) GetF4() []byte {
	if m != nil {
		return m.F4
	}
	return nil
}

func (m *TestMsg) GetF3() uint64 {
	if m != nil {
		return m.F3
	}
	return 0
}

func (m *TestMsg) GetF5() float64 {
	if m != nil {
		return m.F5
	}
	return 0
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "protorec.TestMsg")
}

func init() { proto.RegisterFile("simple_test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xce, 0xcc, 0x2d,
	0xc8, 0x49, 0x8d, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0x45, 0xa9, 0xc9, 0x4a, 0x91, 0x5c, 0xec, 0x21, 0xa9, 0xc5, 0x25, 0xbe, 0xc5, 0xe9, 0x42,
	0x7c, 0x5c, 0x4c, 0x69, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x69, 0x86, 0x60,
	0xbe, 0x91, 0x04, 0x97, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x53, 0x9a, 0x11, 0x98, 0x6f, 0x22, 0x91,
	0xac, 0xc0, 0xa8, 0xc1, 0x13, 0xc4, 0x94, 0x66, 0x02, 0xe6, 0x1b, 0x4b, 0xf0, 0x29, 0x30, 0x6a,
	0xb0, 0x05, 0x31, 0xa5, 0x19, 0x83, 0xf9, 0xa6, 0x12, 0x39, 0x0a, 0x8c, 0x1a, 0x8c, 0x41, 0x4c,
	0x69, 0xa6, 0x49, 0x6c, 0x60, 0x4b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xf2, 0x83,
	0x00, 0x80, 0x00, 0x00, 0x00,
}
